# Generated by Django 5.1.5 on 2025-01-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default="This user hasn't added a bio yet.", max_length=500),
        ),
    ]
